[package]
name = "library"
version = "0.1.0"
edition = "2021"
authors = ["Dyam Daniels"]
description = "A library for testing JNI"
build = "build.rs"

[dependencies]
jni = "0.19.0"
serde = "1.0.73"
reqwest = { version = "0.11.0", features = ["blocking"] }
base64 = "0.13.0"
base58 = "0.2.0"

[lib]
crate-type = ["cdylib"]
name = "jni_library"

#[profile.release]
#panic = "abort"
#lto = true
#
#[profile.debug]
#panic = "abort"
#lto = true
#
#[profile.dev]
#panic = "abort"
#lto = true
#
#[profile.test]
#panic = "abort"
#lto = true

